"""Self-contained HTML drift report (Pro feature)."""

import html
from typing import Any, Dict, List

_SEVERITY = {
    "type_change": ("high", "Type change"),
    "removed_endpoint": ("high", "Endpoint removed"),
    "removed_method": ("high", "Method removed"),
    "removed_field": ("high", "Field removed"),
    "removed_response": ("high", "Response removed"),
    "removed_parameter": ("high", "Parameter removed"),
    "removed_enum": ("high", "Enum value removed"),
    "breaking_change": ("high", "Breaking change"),
    "added_required": ("medium", "Field now required"),
    "added_required_parameter": ("medium", "Parameter now required"),
    "missing_required": ("medium", "Missing required field"),
    "type_mismatch": ("medium", "Type mismatch"),
    "undocumented_field": ("low", "Undocumented field"),
    "enum_violation": ("low", "Enum violation"),
    "one_of": ("low", "Schema mismatch"),
    "probe_error": ("info", "Probe error"),
}

_SEV_COLOR = {
    "high": "#d64545", "medium": "#d99a2b", "low": "#4a90d9", "info": "#8a8a8a",
}


def _esc(s: Any) -> str:
    return html.escape(str(s))


def _severity(finding: Dict[str, Any]) -> str:
    return _SEVERITY.get(finding.get("type"), ("low", finding.get("type", "finding")))[0]


def _label(finding: Dict[str, Any]) -> str:
    return _SEVERITY.get(finding.get("type"), ("low", finding.get("type", "finding")))[1]


def render_html(result: Dict[str, Any], command: str) -> str:
    """Render a check/diff result dict as a single-file HTML report."""
    findings: List[Dict[str, Any]] = result.get("findings", [])
    rows = []
    for f in findings:
        sev = _severity(f)
        rows.append(
            f"<tr>"
            f'<td><span class="sev" style="background:{_SEV_COLOR[sev]}">{sev}</span></td>'
            f"<td class=\"type\">{_esc(f.get('type'))}</td>"
            f"<td class=\"path\">{_esc(f.get('path'))}</td>"
            f"<td>{_esc(f.get('message'))}</td>"
            f"</tr>"
        )

    summary_bits = []
    for key in ("endpoints", "probed", "skipped", "errors"):
        if key in result:
            summary_bits.append(f"{key}: <b>{result[key]}</b>")
    summary = ", ".join(summary_bits) if summary_bits else f"command: {_esc(command)}"

    title = f"DriftWire report — {_esc(command)}"
    body = "".join(rows) if rows else (
        '<tr><td colspan="4" class="ok">✓ no drift detected</td></tr>'
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
         margin: 2rem; color: #1a1a1a; background: #fafafa; }}
  h1 {{ font-size: 1.4rem; }}
  .summary {{ color: #555; margin: .5rem 0 1.5rem; }}
  table {{ border-collapse: collapse; width: 100%; background: #fff; }}
  th, td {{ text-align: left; padding: .55rem .7rem; border-bottom: 1px solid #eee;
           vertical-align: top; font-size: .92rem; }}
  th {{ background: #f0f0f0; font-weight: 600; }}
  .sev {{ color: #fff; padding: .15rem .5rem; border-radius: 3px; font-size: .75rem;
          text-transform: uppercase; letter-spacing: .03em; }}
  .type {{ font-family: ui-monospace, Menlo, monospace; font-size: .85rem; }}
  .path {{ font-family: ui-monospace, Menlo, monospace; font-size: .82rem; color: #333; }}
  .ok {{ color: #2e7d32; font-weight: 600; }}
  footer {{ margin-top: 2rem; color: #999; font-size: .8rem; }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="summary">{summary} — <b>{len(findings)}</b> finding(s)</div>
<table>
<thead><tr><th>Severity</th><th>Type</th><th>Location</th><th>Message</th></tr></thead>
<tbody>
{body}
</tbody>
</table>
<footer>Generated by DriftWire — Meridian Digital</footer>
</body>
</html>
"""
